_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: custom-dataset
epochs:
    value: 100
learning_rate:
    value: 0.0007
